#!/bin/bash

shopt -s nullglob

# git clone git@github.com:philion/etc.git; etc/philstrap/initialize

# a simple init script

# home=$HOME
home=$PWD

# philstrap_home
philstrap_home="$(cd "$(dirname "$0")"; pwd)"

# setup all the links after the git clone

# bin
if [ ! -e "$home/bin" ]
then
    echo making bin
    mkdir -p "$home/bin"
fi

# for each file
echo bin files...
for file in "$philstrap_home/bin/*"
do    
    name=$(basename "$file")
    target="$home/bin/$name"
    
    echo "$file" "$target"
    
    if [ -e "$target" ]
    then
        echo skipping $target
    else
        echo "$file" -> "$target"
        #ln -s "$file" "$target"
    fi
done

# for each dotfile
echo dot files...
for file in "$philstrap_home/dotfiles/dot.*"
do    
    name=$(basename "$file")
    dotname=".${name:4}"
    target="$home/$dotname"
    
    echo "$file" "$target"
    
    if [ -f "$target" ]
    then
        #mv "$home/$dotname" "$home/dot$dotname"
        echo skipping "$target"
    else
        echo "$file" -> "$target"
        #ln -s "$file" "$target"
    fi
done

# git clone git@github.com:philion/etc.git; etc/philstrap/initialize