#!/bin/bash

# git clone git@github.com:philion/etc.git; etc/philstrap/initialize

# a simple init script

# home=$HOME
home=$PWD

# philstrap_home
philstrap_home="$(cd "$(dirname "$0")"; pwd)"

# setup all the links after the git clone

# bin
if [ ! -e "$home/bin" ]
then
    mkdir -p "$home/bin"
fi

# for each file
for file in $philstrap_home/bin/*
do    
    if [ -e "$home/bin/$file" ]
    then
        echo skipping $home/bin/$file
    else
        name=$(basename "$file")
        ln -s "$file" "$home/bin/$name"
    fi
done

# for each dotfile
for file in $philstrap_home/dotfiles/dot.*
do
    name=$(basename "$file")
    dotname=".${name:4}"
    target=
    
    if [ -f "$home/$dotname" ]
    then
        mv "$home/$dotname" "$home/dot$dotname"
    fi
    ln -s "$file" "$home/$dotname"
done

# git clone git@github.com:philion/etc.git; etc/philstrap/initialize